### ISSUE TITLE
Support strongly typed event data

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-functions-eventgrid-extension#11]
Currently `EventGridEvent` is designed with its `Data` property as a `JObject` which will force everyone downstream to get into dealing with converting that into their own strong types using the JSON.NET APIs themselves. 

I propose supporting an `EventGridEvent<T>`  where the `Data` property would now be `T`. This would allow people to use a parameter such as `EventGridEvent<CustomerProfileUpdated>` and it would "just work". Simultaneously we can keep the existing, default `EventGridEvent` by simply changing it to be a subclass of `EventGridEvent<JObject>` that effectively locks it into `JObject` for people who _might_ choose to work with that model instead.

**Comment by ChristianWeyer** [comment]
Is there anything like this planned?
.cc @fabiocav .cc @jeffhollan

**Comment by jeffhollan** [comment]
We just use the EventGrid .net SDK to surface the trigger so it’s likely a better ask for the event grid SDK team. If the SDK supported it functions would “inherit” that functionality. I’ll ping them on this ask and reference the discussion.

**Comment by adrianknight89** [comment]
@jeffhollan Can you give us an update on this? Also, I'd like to see enums for `eventType`. Coding against strings looks unreliable to me.

**Comment by iamalexmang** [comment]
An update would be highly appreciated, @jeffhollan. 
I realize this is not in the Functions' turf, but I appreciate that you could add some weight to this.
I believe that it is childish that the event which is getting a strongly typed object must be read using a key value pair instead.
What's mostly annoying is the *the only* available sample using custom data literally leverages this functionality, but it fires an http-triggered function instead (which is far from ideal for the purpose of the sample): Event Grid triggered functions just be just that, not an http triggered function which pulls the event data, imho.

**Comment by jeffhollan** [comment]
Sure let me send this to the Event Grid team and see if any thoughts on what would be required here and if something that can be committed

**Comment by krb3d** [comment]
Hello there. Any updates on this topic?

**Comment by fnandocontreras** [comment]
+1 Nice to have this feature

**Comment by MattMinke** [comment]
So the EventGrid client library (NuGet: ["Microsoft.Azure.EventGrid"](https://www.nuget.org/packages/Microsoft.Azure.EventGrid/3.2.0)) has a EventGridSubscriber that supports the ability to add custom mappings that will be used during deserialization. With this you can then Cast the Data property to the type you are interested in.  While not exactly what is being asked for this might provide the insight to someone more familiar with the inner working of Azure functions and how the EventGridTrigger works. 

```C#
public void Example(System.IO.Stream inbound)
{
    var eventGridSubscriber = new Microsoft.Azure.EventGrid.EventGridSubscriber();

    eventGridSubscriber.AddOrUpdateCustomEventMapping(
        typeof(MyEvent).FullName,
        typeof(MyEvent));

    var events = eventGridSubscriber.DeserializeEventGridEvents(inbound);

    var myEvent = (MyEvent)events.First().Data;

}
```

NOTE: The Microsoft.Azure.EventGrid package has been deprecated in favor of Azure.Messaging.EventGrid however I think Azure functions are still using the Microsoft.Azure.EventGrid package
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Azure.Messaging.EventGrid/MigrationGuide.md#deserializing-events-and-data


Additional reference material: 

 - https://docs.microsoft.com/en-us/azure/event-grid/receive-events#endpoint-validation
 - https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?view=azure-dotnet#consume-events
 - https://github.com/Azure-Samples/azure-event-grid-viewer/blob/master/viewer/Controllers/UpdatesController.cs

**Comment by shreyabatra4** [comment]
This is available in the new version of bindings (3.x), reference [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid).
