### ISSUE TITLE
Why does EventGridTriggerBinding need to support multiple types to convert from?

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-functions-eventgrid-extension#15]
Hi all, I was attempting to rebase PR #12 on top of the latest changes and ran into an interesting problem. A unit test was written for the EvenGridTriggerBinding::BindAsync method here:

https://github.com/Azure/azure-functions-eventgrid-extension/blob/9a9b3eede0ed1cd65057b24e7734f3aacaf95f3e/test/Extension.tests/UnitTests.cs#L20-L44

This unit test now passes in two totally different types of source values which the "old" `EventGridTriggerBinding` did support. They are `string` and `EventGridEvent`.

The question I have is: why does this binding need to support more than one? The binding itself is an internal class that closely cooperates with `EventGridExtensionConfig`'s `IAsyncConverter<HttpRequestMessage, HttpResponseMessage>` whose responsibility it is to provide the value into the binding... albeit indirectly. Seen here:

https://github.com/Azure/azure-functions-eventgrid-extension/blob/9a9b3eede0ed1cd65057b24e7734f3aacaf95f3e/src/EventGridExtension/EventGridExtensionConfig.cs#L85-L96

In the current implementation, the `EventGridExtensionConfig` is always translating the incoming `HttpRequestMessage` body from JSON into a strongly typed `List<EventGridEvent>` and then triggering the functions with the individual `EventGridEvent` instances. Given that, the binding will never see `string` parameter.

So, that said, while the binding implementation supports converting the raw value from a `string`, it will never have to do that AFAICT and, therefore, the unit test that was added covers a scenario that doesn't really exist and should thus be removed. Additionally I would suggest that the test method is extremely overloaded with way too many responsibilities and should be refactored into multiple tests.

**Comment by drub0y** [comment]
In PR #12 I'm going to go ahead and refactor this test to work against my implementation. I'll push an update to the PR with those changes and await any other feedback the team might have to offer.

**Comment by watashiSHUN** [comment]
...I should track better of the issues
The answer lies in https://github.com/Azure/azure-functions-eventgrid-extension/commit/b6af0dff67a25467d06d1dc528387e4f8f0a2dda
in  short, there is more than 1 way to call `bindAsync`, one of which is through `admin/functions/{name}` api which allows user to pass the function argument in HTTP request body, function runtime will first parse it to string and then invoke user function ([reference](https://github.com/Azure/azure-functions-host/blob/efdd7f9c70983f53b550cd33a42292ffbc497a03/src/WebJobs.Script.WebHost/Controllers/AdminController.cs#L64-L68))

**Comment by sandromastronardi** [comment]
How about the cloudevent schema? i dont see that in the code currently. I see documentation stating that i could just use CloudEvent but the validation fails because there is nothing in there for cloud events?
