### ISSUE TITLE
Cannot get to work with pre-compiled C#

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-eventgrid-extension#17]
I have a project in VS 2017 targeting the v1 runtime.  I have installed the nuget package Microsoft.Azure.WebJobs.Extensions.EventGrid 1.0.0-beta2.

The code (pasting below) builds fine, and publishes fine. I don't see any errors in logs. However it never fires. I create Event Grid functions in the portal in C# Script and they fire - though the data is the same.  The closest thing I can see to a difference is when I use the "Test" button in the UX with the C# Script and pass in a string, the C# Script one that works throws an exception that it can't parse the event.  The C# one (that doesn't work) says function fired and completed, but no exception is thrown.

``` csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.EventGrid;
using Microsoft.Azure.WebJobs.Host;

namespace EventGridBlob
{
    public static class EventGridTrigger
    {
        [FunctionName("EventGridTrigger")]
        public static async Task RunAsync(
            [EventGridTrigger]EventGridEvent myEvent, 
            TraceWriter log)
        {
            log.Info($"Event Grid event recieved {myEvent.EventType}");
        }
    }
}

```

**Comment by watashiSHUN** [comment]
did you create an EventGrid Subscription?

**Comment by jeffhollan** [comment]
Yes - have a repro in shared sub if you want access.  The portal UX would correctly ask to create subscription and generated a webhook but never got invoked

**Comment by drub0y** [comment]
@jeffhollan What version of the EventGrid extension NuGet package do have you referenced? You may know this, but precompiled functions have some funkiness when it comes to assembly binding against assemblies that are provided "in the box", so I just want to make sure you're compiling against the `1.0.0-beta2` version.

I'm not on the Azure Functions team, but I'm happy to check out your source repo too if you want an extra set of eyes. 👀 😉

**Comment by watashiSHUN** [comment]
it is caused by inconsistency between the function name, can you try change
`public static async Task` ~~`RunAsync`~~`()` to `public static async Task EventGridTrigger()`
