### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by glittle** [Azure/azure-functions-eventgrid-extension#24]
Could someone point me to any documentation about how to use the Event Grid extensions?  I haven't found anything that gives any clues as to how it should be used!

I simply want to:

1. Create a subscription in my resource group's event topic (pre-existing) with the prefix I current need to use. This is done at startup my code's startup. If the subscription is already there, I presume I'll just re-use it. The code will supply or update the call-back URL that the Grid needs to use.

2. Respond to events from the Event Grid. 

3. Send events to the Grid.

4. Stop listening (at shutdown).

**Comment by glittle** [comment]
If it is simpler to just use WebClient and a JSON string to do this, that's fine.  Adding this Extension from NuGet ended up adding 55 new packages to my solution! :(

**Comment by watashiSHUN** [comment]
The documentation is being reviewed right now, I will update it once its out.
to send events to the Grid, there is a [nuget package from EventGrid](https://www.nuget.org/packages/Microsoft.Azure.Management.EventGrid/)

this extension is intended for azure functions (where its dependencies are from)
maybe this [blog post](https://medium.com/@tsuyoshiushio/reactive-programming-with-event-grid-and-azure-functions-52b24003935d) will help

**Comment by shreyabatra4** [comment]
Documentation can be found [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid?msclkid=3800ab58d0a411ec86a7a3b5d912720c&tabs=in-process%2Cextensionv3&pivots=programming-language-csharp)
