### ISSUE TITLE
Dependency on Microsoft.Azure.WebJobs .NET 4.6

### ISSUE THREAD

**Issue by bassie1978** [Azure/azure-functions-eventgrid-extension#30]
I'm trying to set up an Azure Function that has an EventGrid trigger in .NET 4.6

The Microsoft.NET.Sdk.Functions 1.0.13 has dependencies to Microsoft.Azure.WebJobs >= 2.2.0 && <2.3.0
The 2.0.0-beta1 extension requires Microsoft.Azure.WebJobs >= 3.0.0-beta5

Am I missing something, or can I not upgrade to the 2.0.0-beta1 version?

**Comment by watashiSHUN** [comment]
for that you need:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/1.0.0-beta4

**[EXPLAINATION]**:
Microsoft.NET.Sdk.Functions 1.0.13 actually targets multiple platforms:
![image](https://user-images.githubusercontent.com/6531400/38527000-7faf97ba-3c0d-11e8-9410-476246ed00cc.png)

EventGrid uses another approach, different package version to target different frameworks:
1.0.0 targets full framework
![image](https://user-images.githubusercontent.com/6531400/38527117-f949747e-3c0d-11e8-9804-8268a1e53775.png)

2.0.0 targets net standard:
![image](https://user-images.githubusercontent.com/6531400/38527106-eb662492-3c0d-11e8-93d5-b1b5a811d738.png)

**Comment by watashiSHUN** [comment]
If you are using visual studio, try the eventgrid template which has the dependency set up:
1. you need VS2017 15.6.5
2. install function extension
![image](https://user-images.githubusercontent.com/6531400/38527236-901eddd0-3c0e-11e8-8578-33720a6b5f00.png)
