### ISSUE TITLE
Event grid subscription not working for Storage Analytics containers?

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-functions-eventgrid-extension#40]
I have created a event grid subscription with topic type as storage account. I want to trigger a Azure function as soon as any new logs get created. I also added a filter prefix /blobServices/default/containers/$logs/. Also logs in $logs container are created by Azure storage Analytics. Though the subscription creation is successful but azure function is not getting triggered. 

Do we need to escape $logs? Or does event grid subscription does not work for special containers like $logs(which are hidden in ui)?

**Comment by watashiSHUN** [comment]
Try testing without filter to verify whether the logs creation trigger events or not?

**Comment by himanshu219** [comment]
Tried testing without filters you are right logs creation events triggered do not include the $logs container while other containers are included

**Comment by watashiSHUN** [comment]
Are you saying that logs creation event **was emitted** but the `subject` looks like this:
`/blobServices/default/containers/blobs/<blobname>`?

**Comment by himanshu219** [comment]
no I don't think event was emitted because I verified in event grid metrics for that event subscription (in azure portal) the outgoing message count was 0.

**Comment by watashiSHUN** [comment]
btw, what is your use case, what is your function trying to do based on the log creation? if you were to process the logs, I believe a lot of the content is about BlobCreated and BlobDeleted event which you can trigger using eventgrid (in a more timely fashion)

**Comment by himanshu219** [comment]
I am using event grid to subscribe to blob creation events and then dumping them to event hub(to act as a buffer). Then as soon as the message is inserted, azure function is getting triggered(using event hub trigger) which reads the logs from the container and send it to another service.

**Comment by watashiSHUN** [comment]
> I am using event grid to subscribe to blob creation events and then dumping them to event hub

You mean subscribe to $log creation? or regular blob creation? I got confirmation from Azure storage team:

> Change notifications are generated for customer initiated PutBlob/PutBlockList/CopyBlob/DeleteBlob calls. Blobs under $logs container are created by Azure storage and notifications will not be generated for them.

But I still don't really understand your use case...so I can't argue the necessity of supporting $log events

**Comment by himanshu219** [comment]
I  meant subscribing to $logs container so that event grid can filter out blob created events and in my azure function I can get the path of newly created blob in $logs container which it can read and send to service.
P.S. my azure function works for other containers but only for $logs it's not working because of the above issue you mentioned.

**Comment by alrod** [comment]
@shreyabatra4 to follow up

**Comment by alrod** [comment]
$logs are not supported in EventGrid:
https://github.com/MicrosoftDocs/azure-docs/issues/42634#issuecomment-588486240
