### ISSUE TITLE
Event Grid Subscription for Event Hub to ingest logs in particular partition

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-functions-eventgrid-extension#41]
While creating event subscription and using eventhub as endpoint there is no way of specifying the partitionID to which all messages should be sent. Is it possible via Webhook? I found that it is possible via Rest API see [here](https://stackoverflow.com/questions/32251517/selecting-partition-of-azure-event-hub-when-using-rest-api). It uses the following url. https://{serviceNamespace}.servicebus.windows.net/{eventHubPath}/publishers/{deviceId}/messages. I am trying to ingest those events to event hub. but what I want is those events to be ingested into a particular partition in event hub.
Is it possible via Event subscription (probably by passing deviceid as parameter)? Or Is there any way to configure event subscription to route those events to a particular partitionID in event hub.

**Comment by jeffhollan** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1750
