### ISSUE TITLE
Release dates?

### ISSUE THREAD

**Issue by denyss-digiterre** [Azure/azure-functions-eventgrid-extension#42]
I don't understand:

1) Which version should I use?
2) Why all versions are (still) in beta?
3) When will it be production-ready?
4) Is there a road-map?
5) How can the engine be not in beta (https://azure.microsoft.com/en-gb/blog/announcing-the-general-availability-of-azure-event-grid/) but the client is still in beta? Is there an SDK I am missing (sorry if this is the case, I am just trying to use NuGet)?

Thank you.

**Comment by shreyabatra4** [comment]
Latest version of extensions can be found [here](https://github.com/Azure/azure-sdk-for-net).
