### ISSUE TITLE
Event Grid “Microsoft.EventHub.CaptureFileCreated” event not published to Azure Function subscription

### ISSUE THREAD

**Issue by riccardobellini** [Azure/azure-functions-eventgrid-extension#44]
I don't know if this is the right place for this issue, since it seems to affect other parts of Azure architecture, not only Azure Function bindings.

I am trying to develop an Azure Function to act upon a blob created by the Capture feature of an Event Hub. However, whereas capture blobs are correctly stored on the container, it seems that no Microsoft.EventHub.CaptureFileCreated event is published to the Function subscription. The event subscription to the function endpoint has been created without errors, and the output from the Azure CLI is

    {
      "additionalProperties": {},
      "deadLetterDestination": null,
      "destination": {
        "additionalProperties": {},
        "endpointBaseUrl": "https://xxxxx-xxxxx-xxxxx.azurewebsites.net/api/EventGridWebhook",
        "endpointType": "WebHook",
        "endpointUrl": null
      },
      "eventDeliverySchema": "InputEventSchema",
      "filter": {
        "additionalProperties": {},
        "includedEventTypes": [
          "Microsoft.EventHub.CaptureFileCreated"
        ],
        "isSubjectCaseSensitive": null,
        "subjectBeginsWith": "",
        "subjectEndsWith": ""
      },
      "id": "/subscriptions/yyyyy-yyyyy-yyyyyy/resourceGroups/test-event-grid-grp/providers/Microsoft.EventHub/namespaces/capture-hub-namespace/providers/Microsoft.EventGrid/eventSubscriptions/captureFunctionV1Sub",
      "labels": null,
      "name": "captureFunctionV1Sub",
      "provisioningState": "Succeeded",
      "resourceGroup": "test-event-grid-grp",
      "retryPolicy": {
        "additionalProperties": {},
        "eventTimeToLiveInMinutes": 1440,
        "maxDeliveryAttempts": 30
      },
      "topic": "/subscriptions/yyyyy-yyyyy-yyyyyy/resourceGroups/test-event-grid-grp/providers/microsoft.eventhub/namespaces/capture-hub-namespace",
      "type": "Microsoft.EventGrid/eventSubscriptions"
    }

The body of the function is a standard Http trigger with the additional validation part needed for the Event Grid endpoint subscription

    public static async Task<object> Run(HttpRequestMessage req, TraceWriter log)
    {
        string jsonContent = await req.Content.ReadAsStringAsync();
        log.Info($"Webhook was triggered! Input: {jsonContent}");
        dynamic events = JsonConvert.DeserializeObject(jsonContent);

        if (req.Headers.GetValues("Aeg-Event-Type").FirstOrDefault() == "SubscriptionValidation")
        {
            var code = events[0].Data["validationCode"];
            return req.CreateResponse(HttpStatusCode.OK,
                new { validationResponse = code });
        }

        return req.CreateResponse(HttpStatusCode.OK);
    }

If I add the same function's endpoint for another type of event (f.i. a blob creation event), I can see the function invocations in the logs. Besides, in the Metrics blade of the event subscription, it seems like no event is ever published to the subscribers (no published, no failed, no unmatched).

Also, it doesn't work with either of the two versions of the runtime environment and even the EventGridTrigger attribute doesn't work.

The same question (with more details) is available on [stackoverflow](https://stackoverflow.com/questions/51173898/event-grid-microsoft-eventhub-capturefilecreated-event-not-published-to-azure).

**Comment by watashiSHUN** [comment]
this is the repository for eventgridTrigger, which is responsible for running your function once event is received. if the event is never fired, not much we can do. But to be honest, eventhub capture is one of the first publisher available with eventgrid, I will be quite surprised if it does not work

I just tried, and functions are triggered correctly, here is my steps
1. create eventhub namespace
2. inside that eventhub namespace, create a eventhub
3. turn on capture, and set time interval to be minimum (so that it triggers function more frequently)
![image](https://user-images.githubusercontent.com/6531400/42394298-84915674-810e-11e8-94a2-23e2a7f7863d.png)
4. create eventgrid trigger function (v1 or v2 should both work)
![image](https://user-images.githubusercontent.com/6531400/42394591-7fdc2a04-810f-11e8-909e-0e85469d285d.png)
5. subscribe from function portal
![image](https://user-images.githubusercontent.com/6531400/42394710-f3650aa4-810f-11e8-9a7b-b821d9a86fb5.png)

**Comment by riccardobellini** [comment]
Yes, unfortunately I didn't know where to write this issue, I understand it is not something strictly related to the Azure Functions binding, but I have not found the official Event Grid issue tracker.

Unfortunately I cannot try the same steps that you have posted until tomorrow, but it seems to me that I have not missed any step, so it should work also for me. The strange thing is that even with other type of subscriptions (logic apps, storage queues) the events are not fired.
Can I ask you the location of the resources you used for your test? I am using West Europe, could a different location have something to do with the issue, maybe event grid is not fully available for all locations?

Thank you very much for your reply.

**Comment by riccardobellini** [comment]
I think it was a temporary issue with the infrastructure. This morning I followed your steps and everything worked. Also, I see the logs of my own function correctly triggered in the past days without me changing anything, now everything runs properly and I can see the published events in the Metrics blade of the event hub namespace.

Thanks for your help.
