### ISSUE TITLE
Fix code issues

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-eventgrid-extension#45]
In reviewing a recent PR, I saw a bunch of stuff which should be fixed:

- many files missing file headers
- EventGridListener should not be public. Some other types are public as well which should probably not be (e.g. SubscriptionValidationResponse)
- EventGridTriggerAttribute should be in the Microsoft.Azure.WebJobs namespace. See all other binding attributes for comparison. This would be a breaking change for v1, but we should fix for v2
- In the v2.x branch, the file EventGridEvent contains 2 types that seem completely unrelated. Are those types even used anymore?

**Comment by shreyabatra4** [comment]
Closing as it is no longer applicable
