### ISSUE TITLE
how do i get the systemkey for event grid trigger function endpoint 

### ISSUE THREAD

**Issue by DebolaA** [Azure/azure-functions-eventgrid-extension#46]
to create an azure function event grid subscription; i need the subscriber endpoint url.

i have tried to get the end point url following the steps mentioned here to no avail
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#create-a-subscription 

someone kindly assist

https://{functionappname}.azurewebsites.net/admin/extensions/EventGridExtensionConfig?functionName={functionname}&code=**{systemkey}**

what i need is the **_system key_** using powershell or ARM or Azure CLi

**Comment by watashiSHUN** [comment]
Sorry for the late replies, did you find a solution, as far as I know it is not exposed through ARM

**Comment by DebolaA** [comment]
yes, found solution. thank you

**Comment by watashiSHUN** [comment]
cool, mind share it? I was going to ask my colleague to add it in ARM...

**Comment by DebolaA** [comment]
@watashiSHUN i will before end of day today

**Comment by DebolaA** [comment]
1. you get the function master code using arm

"outputs": {
    "FunctionAppName": {
        "type": "string",
        "value": "[parameters('functionName')]"
    },
    "Key": {
        "type": "string",
        "value": "[listsecrets(resourceId('Microsoft.Web/sites/functions', parameters('existingFunctionAppName'), parameters('functionName')),'2015-08-01').key]"
    }

2. you call the Invoke-RestMethod https://{functionappname}.azurewebsites.net/admin/host/systemkeys/eventgridextensionconfig_extension?code={function master code}

this returns the system key needed for invoking an Event Grid trigger function. Endpoint url will is in the format shown below:
https://{functionappname}.azurewebsites.net/runtime/webhooks/EventGridExtensionConfig?functionName={function name}&code={system key}

hope this helps. but it will be easier if we can get system from ARM; when the function app is been created.
