### ISSUE TITLE
batching support

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/azure-functions-eventgrid-extension#48]
https://github.com/Azure/azure-webjobs-sdk/commit/0bf125c8e29240ba53027ebaf424ebf2408cf187

**Comment by jeffhollan** [comment]
Would we also utilize queues if message wasn't sent in a batch (e.g. cloud events?) I personally think it makes a lot of sense for consistency of experience but not sure what current behavior here is.

**Comment by alrod** [comment]
Closing as no enough details
