### ISSUE TITLE
BlobCreatedEvent on Blob Copy

### ISSUE THREAD

**Issue by mayoatbm** [Azure/azure-functions-eventgrid-extension#49]
Hey folks,

I'm trying to understand how the event grid blob integration will behave when it comes to async blob copies. Here's what we want

1.  Azure Function A starts an async blob copy from storage account A to B
2. Blob is copied to the new storage account A to B
3. Event Grid notifies Azure Function B that the copy is complete.

Will this scenario work given that the async blob copy creates an empty blob when the copy is initially triggered? We only want the event grid notification after the copy is complete. Is this feasible?

Thanks.

**Comment by jeffhollan** [comment]
@banisadr may be able to connect with the right people to help with this.  I'm not sure how it works.

**Comment by banisadr** [comment]
@mayoatbm let me do a little investigating, I think you will get multiple blob created events, but that the [contentLength property](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage#event-properties) will allow you to ignore the empty blogs in the function

**Comment by mayoatbm** [comment]
@jeffhollan @banisadr  Thanks for looking into this. 

Our scenario involves millions of small blobs so we'd like to avoid double executions of the functions for each one.  I saw that event grid events can be filtered at the subscription level but it doesn't look like we can use properties in the data (only event type and subject).

I think the ideal situation would be for the BlobCreatedEvent to only be sent after the copy is complete, The destination blob can't be manipulated while the copy is pending anyways so it doesn't make sense to notify subscribers at that time. Another option would be way to filter the events to only get notified when the copy is complete.

Thanks again.

**Comment by banisadr** [comment]
@mayoatbm the blob created event only fires when the blob is finished copying successfully - it does not fire when the status is pending, so it should actually work perfectly for your scenario!

**Comment by mayoatbm** [comment]
@banisadr That is wonderful news! We will move forward with implementing this way. Thanks for looking into it so quickly.
